# Generated by Django 5.0.2 on 2024-02-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
